= Chalice Testing

Adapted from link:https://github.com/aws/chalice[this repo]

== Connect to AWS Credentials 

You can use this training with two different types of credentials.  Which credentials you use can be driven by an environment variable on the host


.Valid settings for `AWS_CREDENTIAL_TYPE`
|===
|Value |Meaning

|Canva
|Uses `infra auth` to generate credentials for official Canva AWS accounts

|Burner
|Uses the Burner account Environment variables (see below) to attempt to use AWS SSO signin
|===

=== Burner Credentials

If using the `Burner` credential type, ensure the variables below are set appropriately

|===
| Environment Variable   | Description

| BURNER_SSO_PROFILE
| This should be set to the name of the profile in your `~/.aws/config` file that contains the appropriate Burner Account SSO Login details

| BURNER_AWS_PROFILE
| This should be set to the name of the profile that represents the proper role assumption for the default account you wish to target.  This should also be present in your `~/.aws/config` file
|===

== Terraform Prerequisites

The chalice demo allows the lambda to respond to an SNS topic, but it cannot create the topic.  To create the topic go to the `terraform` directory and run: 
----
terragrunt run-all apply
----

== Creating a Pipeline

[INFO]
====
This is summarized from link:https://aws.github.io/chalice/topics/cd.html[here]
====

A project has already been created by chalice with the `chalice new-project` command

. Go into the `hello-chalice` directory
. If `pipeline-codecommit.json` does not exist already, generate cloud formation for pipeline suitable for deploying chalice
* NOTE: We use the `-b` option to create a CFT that doesn't have the buildspec.yml built in.  We have already defined a buildspec.yml in the root of the repo that deals with the fact that the code is in a sub-directory and not in the root of the repo 
+
----
chalice generate-pipeline --pipeline-version v2 -b /dev/null pipeline-codecommit.json 
----
+
. Now deploy the cloud formation stack created.  This will create a code build pipeline and a CodeCommit repo
+
----
aws cloudformation deploy --stack-name chalice-codecommit --template-file pipeline-codecommit.json --capabilities CAPABILITY_IAM
----
+
. The pipeline will fail b/c the repo is empty.  Run this command to add the created code-commit repo as a remote named `chalice-codecommit` to your repo
+
----
git remote add chalice-codecommit $(echo $(aws cloudformation describe-stacks --stack-name chalice-codecommit --query "Stacks[0].Outputs[?OutputKey=='SourceRepoURL'] | [0].OutputValue") | tr -d '"')
----
+
. Validate that the remote is there with a `git remote -v` if you like:
+
----
chalice-codecommit      https://git-codecommit.ap-southeast-2.amazonaws.com/v1/repos/hello-chalice (fetch)
chalice-codecommit      https://git-codecommit.ap-southeast-2.amazonaws.com/v1/repos/hello-chalice (push)
origin  https://github.com/hatmarch/chalice-testing.git (fetch)
origin  https://github.com/hatmarch/chalice-testing.git (push)
----
+
. Setup a credential helper so that you can access the codecommit repo by role only (FIXME: global is not overriding correctly)
+
----
git config --global credential.https://git-codecommit.$(aws configure get region).amazonaws.com.helper '!aws codecommit credential-helper $@'
git config --global credential.https://git-codecommit.$(aws configure get region).amazonaws.com.UseHttpPath true
----
+
. Now push to remote to start the pipeline (if this fails, see <<Troubleshooting,Troubleshooting>>)
+
----
git push chalice-codecommit
----
+
. At this point, the pipeline should be triggered
+
. When the pipeline is done, you can find your URL like this
+
----
ENDPOINT=$(echo "https://$(aws apigateway get-rest-apis | jq -c '.items[] | select( .name | contains("hello-chalice") ).id' | tr -d '"""').execute-api.$(aws configure get region).amazonaws.com/api")
----
+
. And invoke it like this
+
----
curl -s "${ENDPOINT}" | jq
----

== Troubleshooting

If you have trouble accessing the remote codecommit repo with errors like this:
----
fatal: unable to access 'https://git-codecommit.ap-southeast-2.amazonaws.com/v1/repos/hello-chalice/': The requested URL returned error: 403
----

Then the issue might be the implicit system wide `/etc/gitconfig`

First try:
----
sudo rm /etc/gitconfig
----

And if this doesn't work, you may need to reorder your `~/.gitconfig` so that the credential block for the codecommit repo comes first in the file

== Appendix

See git config
----
git config -l --show-origin | grep credential
----

Set credentials globally with context
----
sudo git config --system credential.https://git-codecommit.ap-southeast-2.amazonaws.com.helper '!aws codecommit credential-helper $@'
----

Get the rest-api id of the resource `$API_NAME` (with quotes stripped out)
----
aws apigateway get-rest-apis | jq -c '.items[] | select( .name | contains("${API_NAME}") ).id' | tr -d '"'
----

Repeatedly call an endpoint waiting for it change
----
while true; do curl -s "${ENDPOINT}" | jq; sleep 1; done
----